### PR TITLE
Master

### PR DESCRIPTION
**Pull request by senkrish**
New pull request against 'develop'. This fix brings in the change to pass the Node object to the plugins so they can generate the resources based on the Node property. This allows for optimization, for instance in the new mysql plugin, where the plugin can generate ALL the node 'variables' with one sql query, based on Node.neighbors.

Testing: I have verified the changes manually, by posting GET and POST request using the urllib2 module. I ran 'make test' to make sure there's no collateral damage. Please let me know if there's any other test I need to run.

I included the mysql plugin in the pull request, I'm not sure if that needs to be merged as it is mostly very specific to my needs. Please remove that file if that is not necessary to be part of the master.

### CODE REVIEW

**Comment by phil-arista** [comment]
This is an awesome little plugin.  My only thinking is that it's very specific to your environment so it might be good to rename it something other than 'mysql' (which is very generic).  That way, others can use this as a good mysql example, but not be fooled into thinking it's a standard mysql client plugin.  What do you think?

**Comment by senkrish** [comment]
Sure, that sounds fine. How about 'nodevar', since i'm fetching 'variables' for the node based on neighbors? I'm not good with names, feel free to suggest better ones.

**Comment by phil-arista** [comment]
Great, could you rename it mysql_vars.  If you update the name and commit we can merge. Thanks!

**Comment by senkrish** [comment]
Renamed to mysql_vars

**Comment by senkrish** [comment]
Done, Also removed ID and tags file I accidentally added earlier.

**Pull request merged**
